language: python
python:
  - "2.7"
install:
  - "sudo mkdir -p /var/log/trebuchet"
  - "sudo chown travis /var/log/trebuchet"
  - "sudo apt-get update"
  - "sudo apt-get install nginx"
  - "sudo rm /etc/nginx/sites-enabled/*"
  - "sudo ln -s /etc/nginx/sites-available/secret_sauce_web_default.conf /etc/nginx/sites-enabled/secret_sauce_web_default.conf"
  - "sudo /etc/init.d/nginx start"
  - "python setup.py install"
script:
  - "trebuchet lint example/application/.missile.yml"
  - "trebuchet build example/application/.missile.yml --output ~/ --arch amd64 --app-version 1.3.4 --env-version 1.4.5 --service-version 1.5.6 --static-version 1.6.7"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.3.4 | wc -l` -eq 1"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.4.5 | wc -l` -eq 1"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.5.6 | wc -l` -eq 3"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.6.7 | wc -l` -eq 1"
  - "trebuchet lint example/product/secret_sauce.yml"
  - "trebuchet build example/product/secret_sauce.yml --output ~/ --arch amd64 --app-version 1.2.3  --static-version 1.7.8"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.2.3 | wc -l` -eq 2"
  - "test `ls -l ~/dh-secret-sauce*.deb | grep 1.7.8 | wc -l` -eq 2"
  - "sudo dpkg -i ~/dh-secret-sauce-lib-1.4.5-amd64.deb ~/dh-secret-sauce-1.3.4-all.deb ~/dh-secret-sauce-web-upstart-1.5.6-all.deb ~/dh-secret-sauce-default-1.2.3-all.deb"
  - "sudo cat /etc/trebuchet/secret_sauce_default.conf"
  - "sudo start dh_secret_sauce_web_upstart_controller"
  - "./example/tests/test_curl.sh 0.0.0.0"

notifications:
  email: false
